In [2]:
import numpy as np
arr=np.array([1,2,3,4,5], dtype=float)
print(arr)
print(arr.dtype)
print(arr.astype(bool))

[1. 2. 3. 4. 5.]
float64
[ True  True  True  True  True]


In [6]:
import numpy as np

array = np.array([1, 2, 3, 4, 5])
arr = np.insert(array, 2, 55)
print(arr)

[ 1  2 55  3  4  5]


In [18]:
import numpy as np

array = np.arange(0,101,2)
print(array)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [13]:
import numpy as np

a = np.array([[1, 2,3], [4, 5,6]])
b = np.array([[1, 2,3], [4, 5,6]])
c=a*b
print(c)



[[ 1  4  9]
 [16 25 36]]


In [56]:
import numpy as np

array = np.array([1, 2, 3, 4, 5])
number = 6
present = False

for num in array: 
    if num == number:
        present = True
        break 

if present:
    print("Present")
else:
    print("Not Present")


Not Present
